### ISSUE TITLE
[WISH] Minor requests about CSV exporting

### ISSUE THREAD

**Issue by gh658804** [mimecorg/webissues#11]
Hi there and thanks to the team for the beta. Nice to see progress in this project.

I haven't fully checked out beta 1 yet so i'm not sure if there is a configuration option for what i'll ask, but for CSV exporting it would be better to be able to define the separator somewhere. Excel by default understands semicolon as separator, so personally, i would prefer to have that as a default separator in my setup.

Also, from what i've seen in the demo page after exporting the "Tasks" item, the "Location" column of each task row is "WebIssues — Tasks". "—" is not a standard character, so perhaps you should consider changing it to a simple "-".

NA

**Comment by mimecorg** [comment]
I think that Excel uses either semicolon or comma as separator depending on the system locale, so it totally makes sense to add an option to configure it. Using "-" in the export is probably also a good idea.
