### ISSUE TITLE
[WISH] Autoselect folder type when only one exists in the list

### ISSUE THREAD

**Issue by gh658804** [mimecorg/webissues#12]
Assume a webissues site in which 2 projects exist, Project1 and Project2. Each project contains a "MyBugs" folder and a "MyTasks" folder. On the leftmost combobox, you select the folder type "Bugs". You then go and select Project1 from the combobox.

Now, at the right of the "Project" combobox, the Folder combobox exists. It has as a default value "All folders". Since it contains **only one** "Bugs" folder (the "MyBugs" one), why not pre-select it? That way, every time you add a new Issue, you will not have to select the "Folder".

**Comment by dickerpulli** [comment]
I definitely would like this feature :-)

**Comment by gh658804** [comment]
Hi.

From what i've understood, you've made this change in the "Add new issue" dialog, which is nice, thanx for it. I was talking about the main grid though. :)

In the main grid (where you see the issues), when a project is selected and the "folders" combobox next to it, contains only one folder of the selected type, it would be nice if that folder was automatically selected.

**Comment by mimecorg** [comment]
In the main grid there is no need to filter the view by the folder if the project only contains one folder of the selected type. I think that this is only useful if there are multiple folders.

**Comment by gh658804** [comment]
Right. So, please ignore my previous comment. :)
