### ISSUE TITLE
[BUG] Site gets "unexpected error" when changing PHP version to 7.2.7 under IIS

### ISSUE THREAD

**Issue by gh658804** [mimecorg/webissues#14]
Well, what the title says...

Changed to php 7.2.7 (Windows 7 pro - IIS express) not for a specific reason, just testing.

v. 7.0.9 and 7.0.33 work fine.

**Comment by mimecorg** [comment]
Is there anything in the PHP error log? I tested it with PHP 7.2 on IIS and it worked fine. Maybe it's some missing extension or something else related to PHP configuration?

**Comment by gh658804** [comment]
OK, after several configurations, installations, uninstallations (even of IIS), i ended up installing php versions 5.3 though 5.6 and now for some reason, i got the same error in v5.6!

I searched around a little bit and i realized that in every version of php i have installed, i had to go and activate the com_dotnet extension. After doing that, it seems to work fine!

Thanks for the pointer.
