### ISSUE TITLE
[BUG] Unexpected Error occurs when search by custom field

### ISSUE THREAD

**Issue by matekhong** [mimecorg/webissues#17]
Search function work properly when search with [ID, Name, Created Date, etc]
but when search with custom field it always show Unexpected error - An internal server error occurred.

**Comment by mimecorg** [comment]
I cannot reproduce this bug. Can you send me the details of the error from the WebIssues event log?

**Comment by matekhong** [comment]
I don't know why currently it's not showing error anymore so I'll close this issue

**Comment by mimecorg** [comment]
This bug can be reproduced if you perform this search as a non-administrator user.
