### ISSUE TITLE
[QUESTION] Is the Email Notification Function is gone is this new version?

### ISSUE THREAD

**Issue by matekhong** [mimecorg/webissues#18]
I've been using Email Notification when Issue has edited in Previous version
https://doc.mimec.org/webissues/1.1/en/webissues.prep.notifications.html

But in current version I've not seen it in Email Setting
Is it gone?

**Comment by mimecorg** [comment]
Email notifications are still available in version 2.0. You can configure sending emails in the server settings (see [sending emails](https://doc.mimec.org/webissues-guide/installation.html#sending-emails) in the guide) and you can set up alerts to define what email notifications are sent (see [alerts](https://doc.mimec.org/webissues-guide/tracking-issues.html#alerts) in the guide).

**Comment by matekhong** [comment]
I've already set as Manual this below is result 
1. Test Button : OK
2. User Register Notification Mail : OK
3. Create new issue and assign to someone : Someone's email not receive notification but on Alert button it show alert notification

What did I miss?

**Comment by mimecorg** [comment]
Is the cron job running?

**Comment by matekhong** [comment]
Not running, is it need?

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by mimecorg** [comment]
Yes, cron is needed for the alert notifications to work. I will update the documentation to make that more clear.

**Comment by matekhong** [comment]
After I've set cron job it work! thank you
