### ISSUE TITLE
date filters do not work when setting a view

### ISSUE THREAD

**Issue by nrossich** [mimecorg/webissues#30]
When using date filters i keep getting an error caused by the format of the data.

We use to work with version 1.1.5 and at the begining of the year we jumped to 2.0 and to in august 2.0.1. 

The funny thing is that we had a big amount of views created on version 1.1.5 with date filters, and worked fine, but when we try to create a new one or when we try to modify the date of an existing one we get this "non-valid format" error.

![image](https://user-images.githubusercontent.com/76204235/102597504-0d6b7280-411b-11eb-8b40-c59c10f4100b.png)

Any ideas?
Thanks!

**Comment by nrossich** [comment]
Hey, it just happens whe we configure the date in spanish format. Now we have set yyyy-mm-dd and it works fine.

![image](https://user-images.githubusercontent.com/76204235/102598989-22e19c00-411d-11eb-970a-71d0b5f3b0a9.png)

Using American date is not an option in for us. cou8ld you give it a check and come back with a solution?

We really appreciate your help!!!

**Comment by mimecorg** [comment]
Thanks for reporting this bug. I already fixed a few issues related to filters, but this looks like a new one, so I'm adding in to my TODO list. I'm planning to release a new version of WebIssues with those bug fixes some time in January, unfortunatelly at the moment I have a very busy period at work.

**Comment by nrossich** [comment]
Dear Michal,

Thanks for your efforts!!! We’ll be expecting for the new release.

BR and happy holidays

El 21 dic 2020, a las 21:55, Michał Męciński <notifications@github.com> escribió:

﻿
Thanks for reporting this bug. I already fixed a few issues related to filters, but this looks like a new one, so I'm adding in to my TODO list. I'm planning to release a new version of WebIssues with those bug fixes some time in January, unfortunatelly at the moment I have a very busy period at work.
