### ISSUE TITLE
Is this project alive, healthy and open to contribution ?

### ISSUE THREAD

**Issue by pvi-github** [mimecorg/webissues#79]
Hello,

I'm searching for a (really) opensource ticketing system for a customer...  

The need is to have a versatile enough ticketing system to manage technical operations in a datacenter.

So we need to link the ticket to an equipment with its location (floor, room, rack number, server number).

The custom fields are a (very) good start be we would have to contribute improvements... plus integration with equiment database systeml, with enterprise directory (LDAP) plus maybe SSO, plus workflow and delegation to manage fine grained approval, and reporting...

Would webissues community be open to such cooperation (discussions about how to do things the right way, review and merging of the pull requests that would be submitted, etc.)

Kind regards,
PV

**Comment by mimecorg** [comment]
Currently I don't have a lot of time to work on WebIssues, but useful pull requests are always welcome.

Regards,
Michał

**Comment by pvi-github** [comment]
Thanks for the answer... my customer chose an other TS with a more vivid community.
Wish you the best...
